### ISSUE TITLE
Does not run in languages other than English

### ISSUE THREAD

**Issue by AltriaChan** [Quorafind/Obsidian-Better-Reading-Mode#14]
![화면 캡처 2023-04-23 143453](https://user-images.githubusercontent.com/59331917/233821677-9f4776b6-892d-4bb7-a71c-04772303f3c2.png)
There is a way to paste the source code of [Jiffy Reader](https://github.com/ansh/jiffyreader.com).

**Comment by ValiHar** [comment]
This feature would be really cool!

**Comment by novelview9** [comment]
I made PR for this
and it is working properly.
![image](https://github.com/Quorafind/Obsidian-Better-Reading-Mode/assets/14916432/a6bc8a2b-8658-4bf3-9445-73581c6aaf45)

https://github.com/Quorafind/Obsidian-Better-Reading-Mode/pull/18#issue-2034423743
