### ISSUE TITLE
[Feature Request] Bionic reading in reading view

### ISSUE THREAD

**Issue by Einspieler19** [Quorafind/Obsidian-Better-Reading-Mode#7]
Is it possible to let bionic reading also work in reading view?

**Comment by Mahgozar** [comment]
I second this 
the annotator plugin makes all the highlight to be in code blocks which are almost only readable in the reading view 
if you could enable this in that mode it would be great

**Comment by ValiHar** [comment]
Yeah this would be really helpful!

**Comment by ProStashio** [comment]
⬆️ I 4th this

**Comment by Bluemoondragon07** [comment]
I 5th this! 😃

**Comment by Quorafind** [comment]
Supported in 2.0.0

**Comment by ProStashio** [comment]
> Supported in 2.0.0

Is this still working? I can't seem to get it to work in reading mode
